version: '3.7'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_HTTP_PORT}:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=${DB_PORT}
      - PMA_USER=root
      - PMA_PASSWORD=${DB_ROOT_PASSWD}
    links:
      - mariadb

  mariadb:
    image: mariadb:10.3.15
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWD}
      - MYSQL_DATABASE=${DB_NAME}