version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./containers/suitecrm/uat/Dockerfile
    volumes:
      - ./app:/var/www/html
      - ./etc/uat/uat.php.ini:/usr/local/etc/php/conf.d/custom-php-ext.ini
      - ./volumes/app/private:/var/www/private
      - ./volumes/app/sessions:/var/www/sessions
      - ./volumes/app/logs/suitecrm:/var/log/suitecrm
      - ./volumes/app/logs/apache2:/var/log/apache2
      - ./volumes/app/logs/cron:/var/log/cron
      - ./volumes/app/logs/php:/var/log/php
      - ./volumes/app/logs/supervisord:/var/log/supervisord
      - ./volumes/app/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    environment:
      - APP_DOMAIN_NAME=${DOMAIN_NAME}
      - APP_USE_SSL=${USE_SSL}
      - APACHE_SERVER_ADMIN_EMAIL=${SERVER_ADMIN_EMAIL}
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - APACHE_ERROR_LOG=/var/log/apache2/error.log
      - APACHE_ACCESS_LOG=/var/log/apache2/access.log
      - APACHE_SSL_ERROR_LOG=/var/log/apache2/ssl_error.log
      - APACHE_SSL_ACCESS_LOG=/var/log/apache2/ssl_access.log
      - SSL_CERTIFICATE_FILE=/etc/letsencrypt/live/${DOMAIN_NAME}/fullchain.pem
      - SSL_CERTIFICATE_KEY_FILE=/etc/letsencrypt/live/${DOMAIN_NAME}/privkey.pem
      - CRON_LOG_FILE=/var/log/cron/cron.log
      - COMPOSER_ALLOW_SUPERUSER=1
    links:
      - mariadb

  mariadb:
    image: mariadb:10.3.15
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWD}
      - MYSQL_DATABASE=${DB_NAME}

  composer:
    image: eclipsehv/cli-php:7.2
    entrypoint: ['composer']
    volumes:
      - ./:/app

  composer_app:
    image: eclipsehv/cli-php:7.2
    entrypoint: ['composer']
    volumes:
      - ./volumes/app/www/:/app

  behat:
    image: eclipsehv/cli-php:7.2
    entrypoint: ['./vendor/bin/behat']
    command: ['--version']
    volumes:
      - ./:/app
    links:
      - selenium

  selenium:
    image: selenium/standalone-chrome-debug:3.11.0-californium
    volumes:
      - ./volumes/selenium/upload:/upload
    environment:
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=1440 #1360 #1200 #900
      - SCREEN_HEIGHT=900 #768 #675
