# Apache2 PHP Container
#
# VERSION               0.1.3

FROM        eclipsehv/apache-php:7.2-dev
MAINTAINER  Riccardo De Leo <riccardo.deleo@unipart.io>

RUN mkdir /var/log/suitecrm
RUN chown -R 1000:1000 /var/log/suitecrm
